### ISSUE TITLE
Whats the reason for the whole interplolation?

### ISSUE THREAD

**Issue by 0xE0-rng** [montioo/ticketbot#2]
Ist there any specific reason, or is it just for the fun of implementing it and over engineering a timer? 😄 
If anyone is wondering thats the function that gets interpolated. 
![grafik](https://user-images.githubusercontent.com/14735397/51218289-fec32200-192b-11e9-9c38-6deaea6f60f6.png)

**Comment by montioo** [comment]
No there isn't a specific reason other than the fun of over engineering a timer 😄 I just thought that the differentiable change in requests per minute looked much nicer than a sudden cut from one rate to another. 

Maybe I should try to learn when a project is done... 

Oh and please excuse my very late answer 😳
